# netlify.toml (Configuration complète)

[build]
  functions = "netlify/functions"

# Redirige les appels d'API vers les fonctions serverless
[[redirects]]
  from = "/auth/discord"
  to = "/.netlify/functions/auth-discord"
  status = 200

[[redirects]]
  from = "/auth/discord/callback"
  to = "/.netlify/functions/auth-discord-callback"
  status = 200

[[redirects]]
  from = "/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/api-user"
  status = 200

[[redirects]]
  from = "/api/generate-key"
  to = "/.netlify/functions/api-generate-key"
  status = 200

# *** REDIRECTION CRUCIALE POUR LA VALIDATION DES CLÉS ***
[[redirects]]
  from = "/api/validate-key"
  to = "/.netlify/functions/api-validate-key"
  status = 200
# ********************************************************

[[redirects]]
  from = "/api/reset-hwid"
  to = "/.netlify/functions/api-reset-hwid"
  status = 200

[[redirects]]
  from = "/api/admin/keys"
  to = "/.netlify/functions/api-admin-keys"
  status = 200
  
[[redirects]]
  from = "/api/send-suggestion"
  to = "/.netlify/functions/api-send-suggestion"
  status = 200

# Règle "catch-all" pour les applications à page unique (SPA)
# Cette règle doit toujours être la dernière
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
