# ✅ netlify.toml — version corrigée

[build]
  functions = "netlify/functions"
  publish = "public"   # <-- remplace "public" si ton dossier build est différent (ex: "dist" ou "build")

[functions]
  node_bundler = "esbuild"   # ✅ évite l’erreur d’upload sur gros fichiers
  included_files = ["netlify/functions/db.js"]  # ✅ force l’inclusion de ton fichier DB local

# Redirections API
[[redirects]]
  from = "/auth/discord"
  to = "/.netlify/functions/auth-discord"
  status = 200

[[redirects]]
  from = "/auth/discord/callback"
  to = "/.netlify/functions/auth-discord-callback"
  status = 200

[[redirects]]
  from = "/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/api-user"
  status = 200

[[redirects]]
  from = "/api/generate-key"
  to = "/.netlify/functions/api-generate-key"
  status = 200

[[redirects]]
  from = "/api/earn-time"
  to = "/.netlify/functions/api-earn-time"
  status = 200

[[redirects]]
  from = "/api/reset-hwid"
  to = "/.netlify/functions/api-reset-hwid"
  status = 200

[[redirects]]
  from = "/api/admin/keys"
  to = "/.netlify/functions/api-admin-keys"
  status = 200
  
[[redirects]]
  from = "/api/send-suggestion"
  to = "/.netlify/functions/api-send-suggestion"
  status = 200

# Règle pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
